/**
 *                                          FULL MOCK DATA
 *          fields:
 *  id
 *  name
 *  company
 *  status            -> stage (new, qualified, contacted, converted, lost)
 *  source
 *  conversionDate    -> present only for converted leads
 *  dealStatus        -> "active" | "close"   <-- (you asked for this)
 *  receivedAmount    -> number (0 if not converted)
 * 
 *  
 */

export const mockData = [
  {
    id: 267881,
    name: "Robert White",
    company: "DataCorp",
    status: "new",
    source: "Referral",
    conversionDate: "2025-01-28",
    dealStatus: "active",
    receivedAmount: 120000,
  },
  {
    id: 498276,
    name: "Chris Evans",
    company: "Techify",
    status: "contacted",
    source: "Website",
    conversionDate: "2025-02-14",
    dealStatus: "close",
    receivedAmount: 95000,
  },
  {
    id: 732145,
    name: "Sarah Kim",
    company: "Innovate Inc.",
    status: "converted",
    source: "Social Media",
    conversionDate: "2025-03-22",
    dealStatus: "close",
    receivedAmount: 175000,
  },
  {
    id: 812364,
    name: "Jason Brown",
    company: "Solutions Co.",
    status: "converted",
    source: "Email Campaign",
    conversionDate: "2025-04-01",
    dealStatus: "close",
    receivedAmount: 140000,
  },
  {
    id: 964523,
    name: "Elizabeth Grey",
    company: "Tech Corp.",
    status: "new",
    source: "Website",
    conversionDate: "2025-04-18",
    dealStatus: "close",
    receivedAmount: 210000,
  },
  {
    id: 174862,
    name: "Laura Green",
    company: "Data Systems",
    status: "converted",
    source: "Referral",
    conversionDate: "2025-05-09",
    dealStatus: "close",
    receivedAmount: 88000,
  },
  {
    id: 653217,
    name: "Kevin Hill",
    company: "Global Softwares",
    status: "converted",
    source: "Cold Call",
    conversionDate: "2025-05-25",
    dealStatus: "close",
    receivedAmount: 165000,
  },
  {
    id: 762931,
    name: "John Doe",
    company: "Innovate Inc.",
    status: "qualified",
    source: "Website",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 849523,
    name: "Jane Smith",
    company: "Solutions Co.",
    status: "new",
    source: "Referral",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 951246,
    name: "Peter Jones",
    company: "Tech Corp.",
    status: "contacted",
    source: "Social Media",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 103852,
    name: "Mary Johnson",
    company: "Innovate Inc.",
    status: "converted",
    source: "Website",
    conversionDate: "2024-01-15",
    dealStatus: "close",
    receivedAmount: 110000,
  },
  {
    id: 118945,
    name: "David Williams",
    company: "Data Systems",
    status: "lost",
    source: "Cold Call",
    conversionDate: "2025-05-25",
    dealStatus: "close",
    receivedAmount: 0,
  },
  {
    id: 129478,
    name: "Emily Brown",
    company: "Solutions Co.",
    status: "new",
    source: "Website",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 137592,
    name: "Michael Davis",
    company: "Tech Corp.",
    status: "qualified",
    source: "Referral",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 148236,
    name: "Sophia Taylor",
    company: "Bright Future Ltd.",
    status: "new",
    source: "Social Media",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 159847,
    name: "Daniel Wilson",
    company: "NextGen Tech",
    status: "contacted",
    source: "Website",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 163924,
    name: "Olivia Martinez",
    company: "Visionary Solutions",
    status: "qualified",
    source: "Referral",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 174658,
    name: "James Anderson",
    company: "Global Softwares",
    status: "converted",
    source: "Email Campaign",
    conversionDate: "2024-02-20",
    dealStatus: "close",
    receivedAmount: 132000,
  },
  {
    id: 186523,
    name: "Ava Thomas",
    company: "Data Systems",
    status: "lost",
    source: "Cold Call",
    conversionDate: "2025-05-25",
    dealStatus: "close",
    receivedAmount: 0,
  },
  {
    id: 197351,
    name: "William Garcia",
    company: "Innovate Inc.",
    status: "qualified",
    source: "Website",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 203467,
    name: "Isabella Martinez",
    company: "Solutions Co.",
    status: "contacted",
    source: "Social Media",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 219456,
    name: "Benjamin Lee",
    company: "Future Tech Ltd.",
    status: "new",
    source: "Referral",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 223785,
    name: "Charlotte Walker",
    company: "Bright Future Ltd.",
    status: "converted",
    source: "Website",
    conversionDate: "2024-03-05",
    dealStatus: "close",
    receivedAmount: 98000,
  },
  {
    id: 234871,
    name: "Lucas Hall",
    company: "Visionary Solutions",
    status: "lost",
    source: "Cold Call",
    conversionDate: "2025-05-25",
    dealStatus: "close",
    receivedAmount: 0,
  },
  {
    id: 247953,
    name: "Mia Young",
    company: "NextGen Tech",
    status: "qualified",
    source: "Social Media",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 258417,
    name: "Ethan Allen",
    company: "Tech Corp.",
    status: "contacted",
    source: "Email Campaign",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 268934,
    name: "Amelia King",
    company: "Global Softwares",
    status: "new",
    source: "Website",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 279846,
    name: "Robert White",
    company: "DataCorp",
    status: "converted",
    source: "Referral",
    conversionDate: "2025-01-28",
    dealStatus: "active",
    receivedAmount: 15000,
  },
  {
    id: 289561,
    name: "Chris Evans",
    company: "Techify",
    status: "converted",
    source: "Website",
    conversionDate: "2025-02-14",
    dealStatus: "close",
    receivedAmount: 12000,
  },
  {
    id: 299817,
    name: "Sarah Kim",
    company: "Innovate Inc.",
    status: "converted",
    source: "Social Media",
    conversionDate: "2025-03-22",
    dealStatus: "active",
    receivedAmount: 18000,
  },
  {
    id: 306784,
    name: "Jason Brown",
    company: "Solutions Co.",
    status: "converted",
    source: "Email Campaign",
    conversionDate: "2025-04-01",
    dealStatus: "close",
    receivedAmount: 20000,
  },
  {
    id: 312958,
    name: "Elizabeth Grey",
    company: "Tech Corp.",
    status: "converted",
    source: "Website",
    conversionDate: "2025-04-18",
    dealStatus: "active",
    receivedAmount: 22000,
  },
  {
    id: 324879,
    name: "Laura Green",
    company: "Data Systems",
    status: "qualified",
    source: "Referral",
    conversionDate: "2025-05-25",
    dealStatus: "active",
    receivedAmount: 0,
  },
  {
    id: 336512,
    name: "John Doe",
    company: "Innovate Inc.",
    status: "qualified",
    source: "Website",
    conversionDate: "2025-05-25",
    dealStatus: "close",
    receivedAmount: 0,
  },
  {
    id: 347916,
    name: "Mary Johnson",
    company: "Innovate Inc.",
    status: "converted",
    source: "Website",
    conversionDate: "2024-01-15",
    dealStatus: "close",
    receivedAmount: 14000,
  },
  {
    id: 358724,
    name: "David Williams",
    company: "Data Systems",
    status: "lost",
    source: "Cold Call",
    conversionDate: "2025-05-25",
    dealStatus: "close",
    receivedAmount: 0,
  },
  {
    id: 369528,
    name: "Michael Davis",
    company: "Tech Corp.",
    status: "qualified",
    source: "Referral",
    conversionDate: "2025-05-25",
    dealStatus: "close",
    receivedAmount: 0,
  },
  {
    id: 372814,
    name: "James Anderson",
    company: "Global Softwares",
    status: "converted",
    source: "Email Campaign",
    conversionDate: "2024-02-20",
    dealStatus: "close",
    receivedAmount: 17500,
  },
];





// Data for the 'Customers' table view
export const customersData = [
  {
    id: 1,
    name: "John Doe",
    company: "Acme Corp",
    email: "john.doe@acmecorp.com",
    phone: "+1 (555) 123-4567",
    product: "CRM Pro Subscription",
    purchaseDate: "2025-08-10",
    value: "$1,200",
    status: "Active",
  },
  {
    id: 2,
    name: "Priya Sharma",
    company: "Sharma Designs",
    email: "priya@sharmadesigns.in",
    phone: "+91 98201 23456",
    product: "Website Design Package",
    purchaseDate: "2025-05-22",
    value: "$850",
    status: "Active",
  },
  {
    id: 3,
    name: "Lucas Martínez",
    company: "TechNova",
    email: "lucas@technova.com",
    phone: "+34 612 345 789",
    product: "Cloud Hosting",
    purchaseDate: "2024-12-01",
    value: "$3,000",
    status: "Inactive",
  },
  {
    id: 4,
    name: "Sarah Kim",
    company: "Bright Marketing",
    email: "sarah.k@brightmarketing.io",
    phone: "+1 (310) 777-9012",
    product: "Email Marketing Suite",
    purchaseDate: "2025-03-15",
    value: "$2,400",
    status: "Active",
  },
];






//supportData
export const supportData = [
  {
    id: "TCK-001",
    customer: "John Doe",
    issue: "Login not working",
    description: "Customer is unable to log into their dashboard using Google sign-in.",
    priority: "High",
    status: "Open",
    assignedTo: "Sarah Kim",
    dateCreated: "2025-11-05",
    lastUpdated: "2025-11-10",
    channel: "Email",
  },
  {
    id: "TCK-002",
    customer: "Priya Sharma",
    issue: "Billing error",
    description: "Invoice shows incorrect amount for September.",
    priority: "Medium",
    status: "In Progress",
    assignedTo: "Lucas Martínez",
    dateCreated: "2025-11-02",
    lastUpdated: "2025-11-08",
    channel: "Chat",
  },
  {
    id: "TCK-003",
    customer: "TechNova Ltd.",
    issue: "Request for data export",
    description: "Customer requested CSV export of all user data for audit purposes.",
    priority: "Low",
    status: "Resolved",
    assignedTo: "John Doe",
    dateCreated: "2025-10-25",
    lastUpdated: "2025-11-01",
    channel: "Phone",
  },
];




export const dealsData = [
  {
    id: "DEAL-001",
    name: "Website Redesign Project",
    company: "Sharma Designs",
    contactPerson: "Priya Sharma",
    stage: "Proposal Sent",
    value: "$3,000",
    probability: 70,
    expectedClose: "2025-11-25",
    status: "Active",
    assignedTo: "Sarah Kim",
    notes: "Waiting for client to review proposal.",
  },
  {
    id: "DEAL-002",
    name: "Cloud Migration Service",
    company: "TechNova Ltd.",
    contactPerson: "Lucas Martínez",
    stage: "Negotiation",
    value: "$12,000",
    probability: 60,
    expectedClose: "2025-12-10",
    status: "Active",
    assignedTo: "John Doe",
    notes: "Negotiation on pricing terms.",
  },
  {
    id: "DEAL-003",
    name: "CRM Subscription Renewal",
    company: "Acme Corp",
    contactPerson: "John Doe",
    stage: "Closed Won",
    value: "$1,200",
    probability: 100,
    expectedClose: "2025-10-30",
    status: "Won",
    assignedTo: "Priya Sharma",
    notes: "Deal successfully renewed for 12 months.",
  },
  {
    id: "DEAL-004",
    name: "Marketing Automation Package",
    company: "Bright Marketing",
    contactPerson: "Sarah Kim",
    stage: "Closed Lost",
    value: "$2,500",
    probability: 0,
    expectedClose: "2025-09-20",
    status: "Lost",
    assignedTo: "Lucas Martínez",
    notes: "Client chose competitor’s product.",
  },
];












// CHECKBOX DATA
// A mock array of tasks with a completed state.
export const CheckBoxData = [
    { id: 1, text: "Follow up with John Doe", completed: false },
    { id: 2, text: "Send contract to Acme Inc", completed: false },
    { id: 3, text: "Call Jane Smith", completed: false },
    { id: 4, text: "Prepare proposal for XYZ.Corp", completed: false },
    { id: 5, text: "Schedule product demo", completed: false },
];







// Data for Meetings
export const mockMeetingsData = [
    { id: 1, title: "Demo Call with Jane Smith", date: "Mar 11, 2024", time: "5:00 PM" },
    { id: 2, title: "Review Meeting with ABC Ltd", date: "Mar 12, 2024", time: "10:00 AM" },
    { id: 3, title: "Follow-up Call with John Doe", date: "Mar 13, 2024", time: "2:00 PM" },
    { id: 4, title: "Client Sync with Tech Solutions", date: "Mar 14, 2024", time: "11:00 AM" },
    { id: 5, title: "Team Standup", date: "Mar 14, 2024", time: "9:00 AM" },
];  